{
  "kind": "discovery#restDescription",
  "baseUrl": "https://www.googleapis.com/drive/v3/",
  "discoveryVersion": "v1",
  "revision": "20230727",
  "version": "v3",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "title": "Google Drive API",
  "name": "drive",
  "batchPath": "batch/drive/v3",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "id": "drive:v3",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/drive/",
  "servicePath": "drive/v3/",
  "ownerName": "Google",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "basePath": "/drive/v3/",
  "resources": {
    "changes": {
      "methods": {
        "getStartPageToken": {
          "flatPath": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "changes/startPageToken",
          "id": "drive.changes.getStartPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "httpMethod": "GET"
        },
        "watch": {
          "path": "changes/watch",
          "id": "drive.changes.watch",
          "description": "Subscribes to changes for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "flatPath": "changes/watch",
          "supportsSubscription": true
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes",
          "path": "changes",
          "httpMethod": "GET",
          "supportsSubscription": true,
          "description": "Lists the changes for a user or shared drive.",
          "id": "drive.changes.list"
        }
      }
    },
    "revisions": {
      "methods": {
        "update": {
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision with patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update"
        },
        "list": {
          "flatPath": "files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "description": "Lists a file's revisions.",
          "httpMethod": "GET"
        },
        "get": {
          "supportsMediaDownload": true,
          "id": "drive.revisions.get",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a revision's metadata or content by ID.",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "delete": {
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content in Google Drive, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "id": "drive.revisions.delete",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "id": "drive.about.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "about",
          "path": "about",
          "description": "Gets information about the user, the user's Drive, and system capabilities.",
          "httpMethod": "GET"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "path": "channels/stop",
          "id": "drive.channels.stop",
          "httpMethod": "POST",
          "flatPath": "channels/stop",
          "description": "Stops watching resources through this channel.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "comments": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.get",
          "description": "Gets a comment by ID."
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments",
          "httpMethod": "POST",
          "description": "Creates a comment on a file.",
          "id": "drive.comments.create",
          "flatPath": "files/{fileId}/comments"
        },
        "delete": {
          "id": "drive.comments.delete",
          "description": "Deletes a comment.",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "id": "drive.comments.update",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "PATCH",
          "description": "Updates a comment with patch semantics.",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.list",
          "path": "files/{fileId}/comments",
          "httpMethod": "GET",
          "description": "Lists a file's comments.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.delete",
          "description": "Deletes a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "DELETE"
        },
        "update": {
          "description": "Updates a permission with patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.update",
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "description": "Gets a permission by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "id": "drive.permissions.list",
          "flatPath": "files/{fileId}/permissions",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists a file's or shared drive's permissions."
        },
        "create": {
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.create",
          "httpMethod": "POST",
          "path": "files/{fileId}/permissions",
          "description": "Creates a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "get": {
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.get"
        },
        "delete": {
          "description": "Deprecated: Use `drives.delete` instead.",
          "id": "drive.teamdrives.delete",
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `drives.list` instead.",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "flatPath": "teamdrives",
          "path": "teamdrives"
        },
        "update": {
          "description": "Deprecated: Use `drives.update` instead.",
          "id": "drive.teamdrives.update",
          "httpMethod": "PATCH",
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "create": {
          "path": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.create",
          "description": "Deprecated: Use `drives.create` instead.",
          "flatPath": "teamdrives",
          "httpMethod": "POST"
        }
      }
    },
    "files": {
      "methods": {
        "update": {
          "flatPath": "files/{fileId}",
          "supportsMediaUpload": true,
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "id": "drive.files.update",
          "httpMethod": "PATCH",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v3/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "id": "drive.files.get"
        },
        "export": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "useMediaDownloadService": true,
          "path": "files/{fileId}/export",
          "supportsMediaDownload": true,
          "id": "drive.files.export",
          "flatPath": "files/{fileId}/export",
          "httpMethod": "GET",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB."
        },
        "watch": {
          "id": "drive.files.watch",
          "path": "files/{fileId}/watch",
          "description": "Subscribes to changes to a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/watch",
          "httpMethod": "POST",
          "supportsSubscription": true
        },
        "delete": {
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "httpMethod": "DELETE",
          "id": "drive.files.delete"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "flatPath": "files",
          "httpMethod": "GET",
          "path": "files",
          "id": "drive.files.list"
        },
        "emptyTrash": {
          "flatPath": "files/trash",
          "id": "drive.files.emptyTrash",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Permanently deletes all of the user's trashed files.",
          "httpMethod": "DELETE"
        },
        "create": {
          "flatPath": "files",
          "supportsMediaUpload": true,
          "description": " Creates a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]",
          "path": "files",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.create"
        },
        "listLabels": {
          "httpMethod": "GET",
          "path": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file.",
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "copy": {
          "description": "Creates a copy of a file and applies any requested updates with patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "path": "files/{fileId}/copy",
          "flatPath": "files/{fileId}/copy",
          "httpMethod": "POST",
          "id": "drive.files.copy"
        },
        "generateIds": {
          "path": "files/generateIds",
          "description": "Generates a set of file IDs which can be provided in create or copy requests.",
          "httpMethod": "GET",
          "flatPath": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.generateIds"
        },
        "modifyLabels": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/modifyLabels",
          "httpMethod": "POST",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "id": "drive.files.modifyLabels",
          "path": "files/{fileId}/modifyLabels"
        }
      }
    },
    "drives": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "path": "drives",
          "description": "Creates a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.create",
          "flatPath": "drives"
        },
        "get": {
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a shared drive's metadata by ID.",
          "id": "drive.drives.get",
          "path": "drives/{driveId}"
        },
        "list": {
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drives",
          "id": "drive.drives.list",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide."
        },
        "unhide": {
          "id": "drive.drives.unhide",
          "description": "Restores a shared drive to the default view.",
          "path": "drives/{driveId}/unhide",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "id": "drive.drives.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "httpMethod": "DELETE"
        },
        "hide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "httpMethod": "POST",
          "id": "drive.drives.hide",
          "flatPath": "drives/{driveId}/hide"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.update",
          "httpMethod": "PATCH",
          "description": "Updates the metadate for a shared drive.",
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}"
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a reply by ID.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "update": {
          "id": "drive.replies.update",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "PATCH",
          "description": "Updates a reply with patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "create": {
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.create",
          "httpMethod": "POST",
          "description": "Creates a reply to a comment."
        },
        "list": {
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists a comment's replies.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "id": "drive.replies.delete",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    }
  },
  "rootUrl": "https://www.googleapis.com/",
  "protocol": "rest"
}